### ISSUE TITLE
Too Large size Transaction handling Issue.

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-frame#168]
Environment]
Our system is handling transfer and staking service.

When it parse Extrinsic info, some Extrinsic is too Large.
So, our Nestjs process returns "[413]: Request Entity Too Large" with 503-statusCode.

My code is below~
const { block } = await provider.rpc.chain.getBlock(blockHash);
param-blockHash : "0x9d2367e567dec5330cc1915d8e78d85b9ecaa6294a9d28fd9a498bc77fa504d2"

The result of block is Too Large!!!

I found that the Extrinsic Info on "astar.subscan.io".
The Extrinsic is "Parachainsystem"-Module and "Enact_authorized_upgrade"-Call.
https://astar.subscan.io/extrinsic/0x9d2367e567dec5330cc1915d8e78d85b9ecaa6294a9d28fd9a498bc77fa504d2

Question1) Can I ignore that kind of Extrinsic for handling transfer and staking?
Question2) Is there another kind of Extrinsic that include too much data?

**Comment by Dinonard** [comment]
Those are system related calls and are not relevant to staking.

There are other extrinsics which include lots of data but none are relevant to balance transfer or staking.
