### ISSUE TITLE
Requesting confirmation for "TooManyUnlockingChunks", "TooManyEraStakeValues" Error.

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-frame#169]
I am running ASTAR staking Service.
I got some network Errors(TooManyUnlockingChunks, TooManyEraStakeValues, StakingWithNoValue).
I want to know on which condition these errors is occurred.

1) TooManyUnlockingChunks
I think that “unlockingChunks” can be saved 4(MAX_UNLOCKING_CHUNKS on “[mock.rs](http://mock.rs/)” in ASTAR-FRAME repository[https://github.dev/AstarNetwork/astar-frame]).
I guess that it occur when “unlockingChunks” is over 5. Can you confirm that the condition(“unlockingChunks” <= 4) is true?
```
{
  "locked": “###, ###, ###,
  "unbondingInfo": {
    "unlockingChunks": [
      {
        "amount": "###, ###, ###",
        "unlockEra": "455"
      },
      {
        "amount": "###, ###, ###",
        "unlockEra": "457"
      },
      {
        "amount": "###, ###, ###",
        "unlockEra": "458"
      }
    ]
  },
  "rewardDestination": "StakeBalance"
}
```

2) TooManyEraStakeValues
I think that “stakes” can be saved 4(MAX_NUMBER_OF_STAKERS on “[mock.rs](http://mock.rs/)” in ASTAR-FRAME repository[https://github.dev/AstarNetwork/astar-frame]).
I guess that it occur when “stakes” is over 5. Can you confirm that the condition(“stakes” <= 4) is true?
```
[
  {
    "Wasm": "a8SVGV6X5vpZyq85A9mscME9Y7k91LGbhfpB7KjcbtDDUHK",
    "stakes": [
      {
        "staked": "###, ###, ###",
        "era": "449"
      },
      {
        "staked": "###, ###, ###",
        "era": "450"
      }
    ]
  }
]
```

**Comment by Dinonard** [comment]
I suggest to check the errors here & their usage:
https://github.com/AstarNetwork/astar-frame/blob/polkadot-v0.9.39/frame/dapps-staking/src/pallet/mod.rs#L255
