### ISSUE TITLE
Some changes at account.data on Shibuya-Testnet

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-frame#170]
I found a modified part while performing the balance inquiry on "SHIBUYA-TESTNET."
I conducted the balance inquiry with the following code and changed the key value for the data as follows:

`
const accountBalInfo = await this.client.query.system.account("WcuUpmspMcykJdngmUW9nC4YssuoqvRKnMh69gkmBvFFM95");
`

[RESULT-DATA][ASTAR-MAINNET || About 2weeks ago-SHIBUYA-TESTNET]
...
  'data' => Type(4) [Map] {
    'free' => <BN: 2386f26fc10000>,
    'reserved' => <BN: 0>,
    '**miscFrozen**' => <BN: 0>,
    '**feeFrozen**' => <BN: 0>,  
...

[RESULT-DATA][20230817-SHIBUYA-TESTNET]
...
  'data' => Type(4) [Map] {
    'free' => <BN: 5f852b087ee508512>,
    'reserved' => <BN: 0>,
    '**frozen**' => <BN: 44a284cdb24ab21e2>,
    '**flags**' => <BN: 80000000000000044a284cdb24ab21e2>,
...

Q1) Is the change temporary and will it also be applied to the ASTAR mainnet in the future? I'm curious if there are any other changes as well.
Q2) Among the changes, the values for the "flags" appear to be unusual.
I expect to the "flags" is 44a284cdb24ab21e2, but it is 80000000000000044a284cdb24ab21e2.

**Comment by ashutoshvarma** [comment]
This is expected behaviour, it is due to recent changes in `pallet_balances` in v43 release of substrate, see the PR here - https://github.com/paritytech/substrate/pull/12951

> Is the change temporary and will it also be applied to the ASTAR mainnet in the future? I'm curious if there are any other changes as well.

Yes, Astar will be upgraded with new release soon that will include this

**Comment by johnnyji-dev** [comment]
> 

Thanks for your response~
