### ISSUE TITLE
What's the difference between claim_staker and claim_dapp in DappsStaking.sol?

### ISSUE THREAD

**Issue by LaceLetho** [AstarNetwork/astar-frame#36]
**Description**

> I'm planing to utilize the DappStaking.sol to build a dAppStaking contract, but I'm confused about the difference of the two functions, would you mind have an explanation?

Thanks

**Comment by Dinonard** [comment]
Hello,

`claim_staker` will claim staker rewards for a single era (oldest one).
`claim_dapp` will claim dapp rewards for the specified era.

You can find the source code of these functions [here](https://github.com/AstarNetwork/astar-frame/blob/polkadot-v0.9.17/frame/dapps-staking/src/pallet/mod.rs#L710).
We will make a more comprehensive documentation of the linked file soon.

**Comment by LaceLetho** [comment]
Got it, it's clearly explained in the source code.

Thanks
